name: Pull request check

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv sync
      - name: Format check with black
        run: scripts/check_black.sh all
      - name: Static analysis with flake8
        run: scripts/check_flake8.sh all
      - name: Static type checking with mypy
        run: scripts/check_mypy.sh all
      - name: Run unit tests
        run: scripts/check_tests.sh